<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert([
            [
                'id' => 1,
                'name' => 'Matthew',
                'code' => 'CR/001/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Mathew.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 2,
                'name' => 'Mark',
                'code' => 'CR/002/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Mark.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 3,
                'name' => 'Luke',
                'code' => 'CR/003/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Luke.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 4,
                'name' => 'John',
                'code' => 'CR/004/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of John.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 5,
                'name' => 'Acts',
                'code' => 'CR/005/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Acts.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 6,
                'name' => 'Romans',
                'code' => 'CR/006/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Romans.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 7,
                'name' => 'Corinthians',
                'code' => 'CR/007/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Corinthians.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
            [
                'id' => 8,
                'name' => 'Galatians',
                'code' => 'CR/008/25',
                'credit_hours' => 4,
                'duration' => 3,
                'description' => 'Exegesis on the book of Galatians.',
                'is_training' => 0,
                'status' => 1,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
                'created_at' => '2025-04-15 05:27:21',
                'updated_at' => '2025-04-15 05:27:21',
            ],
        ]);
    }
}
