<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert(array_map(function ($course, $i) {
            $course['created_at'] = Carbon::now();
            $course['updated_at'] = Carbon::now();
            return $course;
        }, [
            // Sorted by 'id'
            [
                'id' => 1,
                'name' => 'BBS101 OT survey',
                'credit_hours' => 3,
                'description' => 'BBS101 OT survey',
                'code' => 'CR/001',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 2,
                'name' => 'BBS102 NT survey',
                'credit_hours' => 3,
                'description' => 'BBS102 NT survey',
                'code' => 'CR/002',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 3,
                'name' => 'BBS103 Hermeneutics',
                'credit_hours' => 3,
                'description' => 'BBS103 Hermeneutics',
                'code' => 'CR/003',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 4,
                'name' => 'BTS101 Major Christian Doctrine',
                'credit_hours' => 3,
                'description' => 'BTS101 Major Christian Doctrine',
                'code' => 'CR/004',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 5,
                'name' => 'BTS102 History of Christian Doctrine',
                'credit_hours' => 3,
                'description' => 'BTS102 History of Christian Doctrine',
                'code' => 'CR/005',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 6,
                'name' => 'BGS 105 Communicative English',
                'credit_hours' => 3,
                'description' => 'BGS 105 Communicative English',
                'code' => 'CR/006',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 7,
                'name' => 'BBS207 NT Exegesis',
                'credit_hours' => 3,
                'description' => 'BBS207 NT Exegesis',
                'code' => 'CR/007',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 8,
                'name' => 'BTS 205 Biblical Theology of Healing',
                'credit_hours' => 3,
                'description' => 'BTS 205 Biblical Theology of Healing',
                'code' => 'CR/008',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 9,
                'name' => 'BTS 206 Biblical Theology of Faith, Wealth, Work and Environment',
                'credit_hours' => 2,
                'description' => 'BTS 206 Biblical Theology of Faith, Wealth, Work and Environment',
                'code' => 'CR/009',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 10,
                'name' => 'BCL201 Biblical Leadership',
                'credit_hours' => 3,
                'description' => 'BCL201 Biblical Leadership',
                'code' => 'CR/010',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 11,
                'name' => 'BCL202 Church Administration',
                'credit_hours' => 3,
                'description' => 'BCL202 Church Administration',
                'code' => 'CR/011',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 12,
                'name' => 'BMS 203 Evangelism and Church Planting',
                'credit_hours' => 3,
                'description' => 'BMS 203 Evangelism and Church Planting',
                'code' => 'CR/012',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 13,
                'name' => 'BCP 203 Theology of Praise, worship and practices',
                'credit_hours' => 3,
                'description' => 'BCP 203 Theology of Praise, worship and practices',
                'code' => 'CR/013',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 14,
                'name' => 'Greek I',
                'credit_hours' => 3,
                'description' => 'Greek I',
                'code' => 'CR/014',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 15,
                'name' => 'Greek II',
                'credit_hours' => 3,
                'description' => 'Greek II',
                'code' => 'CR/015',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 16,
                'name' => 'Senior Paper',
                'credit_hours' => 4,
                'description' => 'Senior Paper',
                'code' => 'CR/016',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 17,
                'name' => 'BCP 204 Making Disciples',
                'credit_hours' => 2,
                'description' => 'BCP 204 Making Disciples',
                'code' => 'CR/017',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 18,
                'name' => 'BBS308 Book of Isaiah',
                'credit_hours' => 3,
                'description' => 'BBS308 Book of Isaiah',
                'code' => 'CR/018',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 19,
                'name' => 'BBS310 The Gospel of John',
                'credit_hours' => 3,
                'description' => 'BBS310 The Gospel of John',
                'code' => 'CR/019',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 20,
                'name' => 'BBS309 Synoptic Gospel (one)',
                'credit_hours' => 3,
                'description' => 'BBS309 Synoptic Gospel (one)',
                'code' => 'CR/020',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 21,
                'name' => 'BTS300 Christology',
                'credit_hours' => 3,
                'description' => 'BTS300 Christology',
                'code' => 'CR/021',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 22,
                'name' => 'BTS 304 Pneumatology',
                'credit_hours' => 3,
                'description' => 'BTS 304 Pneumatology',
                'code' => 'CR/022',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 23,
                'name' => 'BCL 303 Strategic Planning',
                'credit_hours' => 2,
                'description' => 'BCL 303 Strategic Planning',
                'code' => 'CR/023',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 24,
                'name' => 'BCL304 Team leadership',
                'credit_hours' => 2,
                'description' => 'BCL304 Team leadership',
                'code' => 'CR/024',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 25,
                'name' => 'BCL305 Conflict resolution',
                'credit_hours' => 3,
                'description' => 'BCL305 Conflict resolution',
                'code' => 'CR/025',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 26,
                'name' => 'BCL306 Managing Change and Time in Organization',
                'credit_hours' => 2,
                'description' => 'BCL306 Managing Change and Time in Organization',
                'code' => 'CR/026',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 27,
                'name' => 'BCL308 Leadership Development',
                'credit_hours' => 3,
                'description' => 'BCL308 Leadership Development',
                'code' => 'CR/027',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 28,
                'name' => 'BMS301 Biblical Theology of Mission',
                'credit_hours' => 3,
                'description' => 'BMS301 Biblical Theology of Mission',
                'code' => 'CR/028',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 29,
                'name' => 'BMS 302 Gospel and Culture',
                'credit_hours' => 3,
                'description' => 'BMS 302 Gospel and Culture',
                'code' => 'CR/029',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 30,
                'name' => 'BMS 308 Missional Church',
                'credit_hours' => 3,
                'description' => 'BMS 308 Missional Church',
                'code' => 'CR/030',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 31,
                'name' => 'BCP301 Christian Counseling',
                'credit_hours' => 3,
                'description' => 'BCP301 Christian Counseling',
                'code' => 'CR/031',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 32,
                'name' => 'BCP 302 Homiletics',
                'credit_hours' => 3,
                'description' => 'BCP 302 Homiletics',
                'code' => 'CR/032',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 33,
                'name' => 'BTS 309 Ecclesiology and Eschatology',
                'credit_hours' => 2,
                'description' => 'BTS 309 Ecclesiology and Eschatology',
                'code' => 'CR/033',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 34,
                'name' => 'BHS 301 Global History of Christianity',
                'credit_hours' => 3,
                'description' => 'BHS 301 Global History of Christianity',
                'code' => 'CR/034',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 35,
                'name' => 'BHS 302 Ethiopian Church History',
                'credit_hours' => 3,
                'description' => 'BHS 302 Ethiopian Church History',
                'code' => 'CR/035',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 36,
                'name' => 'BSF 301 Spiritual Formation',
                'credit_hours' => 2,
                'description' => 'BSF 301 Spiritual Formation',
                'code' => 'CR/036',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 37,
                'name' => 'BSF 302 Supervised Ministry',
                'credit_hours' => 4,
                'description' => 'BSF 302 Supervised Ministry',
                'code' => 'CR/037',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 38,
                'name' => 'BGS301 Teaching Theories, Methods, and Models',
                'credit_hours' => 3,
                'description' => 'BGS301 Teaching Theories, Methods, and Models',
                'code' => 'CR/038',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 39,
                'name' => 'BGS 302 Academic Writing',
                'credit_hours' => 3,
                'description' => 'BGS 302 Academic Writing',
                'code' => 'CR/039',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 40,
                'name' => 'BBS413 NT Theology',
                'credit_hours' => 3,
                'description' => 'BBS413 NT Theology',
                'code' => 'CR/040',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 41,
                'name' => 'BBS 414 Pentateuch',
                'credit_hours' => 3,
                'description' => 'BBS 414 Pentateuch',
                'code' => 'CR/041',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 42,
                'name' => 'BBS415 The Book of Revelation',
                'credit_hours' => 3,
                'description' => 'BBS415 The Book of Revelation',
                'code' => 'CR/042',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 43,
                'name' => 'BBS410 The Letter to the Romans',
                'credit_hours' => 3,
                'description' => 'BBS410 The Letter to the Romans',
                'code' => 'CR/043',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 44,
                'name' => 'BBS411 First Corinthians',
                'credit_hours' => 3,
                'description' => 'BBS411 First Corinthians',
                'code' => 'CR/044',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 45,
                'name' => 'BTS 407 Christianity and Ethnic Identity',
                'credit_hours' => 3,
                'description' => 'BTS 407 Christianity and Ethnic Identity',
                'code' => 'CR/045',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 46,
                'name' => 'BTS 408 Biblical Theology of Peace, Kingdom and Politics',
                'credit_hours' => 2,
                'description' => 'BTS 408 Biblical Theology of Peace, Kingdom and Politics',
                'code' => 'CR/046',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 47,
                'name' => 'BCL407 Philosophy of Leadership',
                'credit_hours' => 3,
                'description' => 'BCL407 Philosophy of Leadership',
                'code' => 'CR/047',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 48,
                'name' => 'BCL409 Leadership Communication',
                'credit_hours' => 3,
                'description' => 'BCL409 Leadership Communication',
                'code' => 'CR/048',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 49,
                'name' => 'BCL410 Leadership in Mission',
                'credit_hours' => 3,
                'description' => 'BCL410 Leadership in Mission',
                'code' => 'CR/049',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 50,
                'name' => 'BCL411 Project Management',
                'credit_hours' => 2,
                'description' => 'BCL411 Project Management',
                'code' => 'CR/050',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 51,
                'name' => 'BCL412 Organizational Leadership',
                'credit_hours' => 3,
                'description' => 'BCL412 Organizational Leadership',
                'code' => 'CR/051',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 52,
                'name' => 'BMS 404 African Traditional Religion',
                'credit_hours' => 3,
                'description' => 'BMS 404 African Traditional Religion',
                'code' => 'CR/052',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 53,
                'name' => 'BMS405 Muslim Teaching, Culture and Evangelism',
                'credit_hours' => 3,
                'description' => 'BMS405 Muslim Teaching, Culture and Evangelism',
                'code' => 'CR/053',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 54,
                'name' => 'BMS406 Christian-Muslim Controversy',
                'credit_hours' => 3,
                'description' => 'BMS406 Christian-Muslim Controversy',
                'code' => 'CR/054',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 55,
                'name' => 'BMS 407 Cultural Anthropology',
                'credit_hours' => 3,
                'description' => 'BMS 407 Cultural Anthropology',
                'code' => 'CR/055',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 56,
                'name' => 'BBS417 The Book of Acts',
                'credit_hours' => 3,
                'description' => 'BBS417 The Book of Acts',
                'code' => 'CR/056',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 57,
                'name' => 'BCP405 Church and Society',
                'credit_hours' => 3,
                'description' => 'BCP405 Church and Society',
                'code' => 'CR/057',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 58,
                'name' => 'BBS416 Pastoral Epistles',
                'credit_hours' => 3,
                'description' => 'BBS416 Pastoral Epistles',
                'code' => 'CR/058',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 59,
                'name' => 'BCP406 Ministry to Children',
                'credit_hours' => 3,
                'description' => 'BCP406 Ministry to Children',
                'code' => 'CR/059',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 60,
                'name' => 'BCP407 Christian Marriage',
                'credit_hours' => 3,
                'description' => 'BCP407 Christian Marriage',
                'code' => 'CR/060',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 61,
                'name' => 'BCP408 Christian Ethics and Ethos',
                'credit_hours' => 3,
                'description' => 'BCP408 Christian Ethics and Ethos',
                'code' => 'CR/061',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 62,
                'name' => 'BGS403 Introduction to Sociology',
                'credit_hours' => 3,
                'description' => 'BGS403 Introduction to Sociology',
                'code' => 'CR/062',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                    'id' => 63,
                    'name' => 'BGS404 Introduction to Anthropology',
                    'credit_hours' => 3,
                    'description' => 'BGS404 Introduction to Anthropology',
                    'code' => 'CR/063',
                    'is_training' => 0,
                    'status' => 1,
                    'duration' => 4,
                    'is_deleted' => 0,
                    'is_published' => 1,
                    'is_approved' => 1,
                    'is_completed' => 0,
            ]
        ], range(0, 62)));
    }
}
