<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('courses')->insert(array_map(function ($course, $i) {
            $course['code'] = 'CR/' . str_pad($i + 1, 3, '0', STR_PAD_LEFT);
            $course['created_at'] = Carbon::now();
            $course['updated_at'] = Carbon::now();
            return $course;
        }, [
            // Sorted by 'name'
            [
                'id' => 1,
                'name' => 'African Traditional Religion',
                'credit_hours' => 3,
                'description' => 'African Traditional Religion',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Book of Isaiah',
                'credit_hours' => 3,
                'description' => 'Book of Isaiah',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 2,
                'name' => 'Biblical Theology of Healing',
                'credit_hours' => 3,
                'description' => 'Biblical Theology of Healing',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 3,
                'name' => 'Biblical Theology of Faith, Wealth, Work and Environment',
                'credit_hours' => 3,
                'description' => 'Biblical Theology of Faith, Wealth, Work and Environment',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 4,
                'name' => 'Biblical Theology of Mission',
                'credit_hours' => 3,
                'description' => 'Biblical Theology of Mission',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Biblical Theology of Peace, Kingdom and Politics',
                'credit_hours' => 3,
                'description' => 'Biblical Theology of Peace, Kingdom and Politics',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Biblical Leadership',
                'credit_hours' => 3,
                'description' => 'Biblical Leadership',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Christology',
                'credit_hours' => 3,
                'description' => 'Christology',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Christian Ethics and Ethos',
                'credit_hours' => 3,
                'description' => 'Christian Ethics and Ethos',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Christian Counseling',
                'credit_hours' => 3,
                'description' => 'Christian Counseling',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Christian Marriage',
                'credit_hours' => 3,
                'description' => 'Christian Marriage',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Christianity and Ethnic Identity',
                'credit_hours' => 3,
                'description' => 'Christianity and Ethnic Identity',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Church Administration',
                'credit_hours' => 3,
                'description' => 'Church Administration',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 14,
                'name' => 'Church and Society',
                'credit_hours' => 3,
                'description' => 'Church and Society',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 15,
                'name' => 'Conflict Resolution',
                'credit_hours' => 3,
                'description' => 'Conflict Resolution',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 56,
                'name' => 'Cross Cultural Communication',
                'credit_hours' => 3,
                'description' => 'Cross Cultural Communication',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 16,
                'name' => 'Cultural Anthropology',
                'credit_hours' => 3,
                'description' => 'Cultural Anthropology',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 17,
                'name' => 'Ecclesiology and Eschatology',
                'credit_hours' => 2,
                'description' => 'Ecclesiology and Eschatology',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 18,
                'name' => 'Ethiopian Church History',
                'credit_hours' => 3,
                'description' => 'Ethiopian Church History',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 19,
                'name' => 'Evangelism and Church Planting',
                'credit_hours' => 3,
                'description' => 'Evangelism and Church Planting',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 20,
                'name' => 'First Corinthians',
                'credit_hours' => 3,
                'description' => 'First Corinthians',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 23,
                'name' => 'Greek I',
                'credit_hours' => 3,
                'description' => 'Greek I',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 24,
                'name' => 'Greek II',
                'credit_hours' => 3,
                'description' => 'Greek II',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 21,
                'name' => 'Global History of Christianity',
                'credit_hours' => 3,
                'description' => 'Global History of Christianity',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 22,
                'name' => 'Gospel and Culture',
                'credit_hours' => 3,
                'description' => 'Gospel and Culture',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 25,
                'name' => 'Hermeneutics',
                'credit_hours' => 3,
                'description' => 'Hermeneutics',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 26,
                'name' => 'History of Christian Doctrine',
                'credit_hours' => 3,
                'description' => 'History of Christian Doctrine',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 27,
                'name' => 'Homiletics',
                'credit_hours' => 3,
                'description' => 'Homiletics',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 29,
                'name' => 'Leadership Communication',
                'credit_hours' => 3,
                'description' => 'Leadership Communication',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 30,
                'name' => 'Leadership Development',
                'credit_hours' => 3,
                'description' => 'Leadership Development',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 31,
                'name' => 'Leadership in Mission',
                'credit_hours' => 3,
                'description' => 'Leadership in Mission',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 32,
                'name' => 'Making Disciples',
                'credit_hours' => 2,
                'description' => 'Making Disciples',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 33,
                'name' => 'Managing Change and Time in Organization',
                'credit_hours' => 2,
                'description' => 'Managing Change and Time in Organization',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 34,
                'name' => 'Major Christian Doctrine',
                'credit_hours' => 3,
                'description' => 'Major Christian Doctrine',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 35,
                'name' => 'Ministry to Children',
                'credit_hours' => 3,
                'description' => 'Ministry to Children',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 36,
                'name' => 'Missional Church',
                'credit_hours' => 3,
                'description' => 'Missional Church',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 37,
                'name' => 'Muslim Teaching, Culture and Evangelism',
                'credit_hours' => 3,
                'description' => 'Muslim Teaching, Culture and Evangelism',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 38,
                'name' => 'NT Survey',
                'credit_hours' => 3,
                'description' => 'NT Survey',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 40,
                'name' => 'NT Exegesis',
                'credit_hours' => 3,
                'description' => 'NT Exegesis',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 39,
                'name' => 'NT Theology',
                'credit_hours' => 3,
                'description' => 'NT Theology',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 41,
                'name' => 'OT Survey',
                'credit_hours' => 3,
                'description' => 'OT Survey',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 42,
                'name' => 'Organizational Leadership',
                'credit_hours' => 3,
                'description' => 'Organizational Leadership',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 43,
                'name' => 'Pastoral Epistles',
                'credit_hours' => 3,
                'description' => 'Pastoral Epistles',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 44,
                'name' => 'Pentateuch',
                'credit_hours' => 3,
                'description' => 'Pentateuch',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 45,
                'name' => 'Philosophy of Leadership',
                'credit_hours' => 3,
                'description' => 'Philosophy of Leadership',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 46,
                'name' => 'Pneumatology',
                'credit_hours' => 3,
                'description' => 'Pneumatology',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 47,
                'name' => 'Project Management',
                'credit_hours' => 3,
                'description' => 'Project Management',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 48,
                'name' => 'Strategic Planning',
                'credit_hours' => 2,
                'description' => 'Strategic Planning',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 49,
                'name' => 'Synoptic Gospel (one)',
                'credit_hours' => 3,
                'description' => 'Synoptic Gospel (one)',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 50,
                'name' => 'Team Leadership',
                'credit_hours' => 2,
                'description' => 'Team Leadership',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 51,
                'name' => 'The Book of Acts',
                'credit_hours' => 3,
                'description' => 'The Book of Acts',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 52,
                'name' => 'The Book of Revelation',
                'credit_hours' => 3,
                'description' => 'The Book of Revelation',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 53,
                'name' => 'The Gospel of John',
                'credit_hours' => 3,
                'description' => 'The Gospel of John',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 54,
                'name' => 'The Letter to the Romans',
                'credit_hours' => 3,
                'description' => 'The Letter to the Romans',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ],
            [
                'id' => 55,
                'name' => 'Theology of Praise, Worship and Practices',
                'credit_hours' => 3,
                'description' => 'Theology of Praise, Worship and Practices',
                'is_training' => 0,
                'status' => 1,
                'duration' => 4,
                'is_deleted' => 0,
                'is_published' => 1,
                'is_approved' => 1,
                'is_completed' => 0,
            ]
        ], range(0, 54)));
    }
}
