<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurriculumSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $curricula = [
            [
                'id' => 1,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 1,
                'year_level' => 1,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 2,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 2,
                'year_level' => 1,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 3,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 4,
                'year_level' => 1,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 4,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 3,
                'year_level' => 1,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 5,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 64,
                'year_level' => 1,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 6,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 65,
                'year_level' => 1,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 7,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 5,
                'year_level' => 1,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 8,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 14,
                'year_level' => 1,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 9,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 6,
                'year_level' => 1,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 10,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 15,
                'year_level' => 1,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 11,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 10,
                'year_level' => 2,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 12,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 13,
                'year_level' => 2,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 13,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 12,
                'year_level' => 2,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 14,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 17,
                'year_level' => 2,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 15,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 8,
                'year_level' => 2,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 16,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 33,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 17,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 9,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 18,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 7,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 19,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 11,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 20,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 26,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 21,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 18,
                'year_level' => 2,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 22,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 34,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 32,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 31,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 25,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 21,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 24,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 28,
                'year_level' => 3,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 28,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 22,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 20,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 35,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 31,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 39,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 32,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 29,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 33,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 25,
                'year_level' => 3,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 34,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 41,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 35,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 44,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 36,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 66,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 37,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 57,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 38,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 43,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 39,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 61,
                'year_level' => 4,
                'semester_level' => 1,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 40,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 42,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 41,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 47,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 42,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 49,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 43,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 58,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 44,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 52,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 45,
                'track_id' => 1,
                'study_mode_id' => 1,
                'course_id' => 16,
                'year_level' => 4,
                'semester_level' => 2,
                'description' => 'This Course In This Study MOde And Track Should Be Taken',
                'active' => 0,
                'created_at' => null,
                'updated_at' => null,
            ],
        ];

        // Get all valid course IDs from the courses table
        $validCourseIds = DB::table('courses')->pluck('id')->toArray();

        // Filter curricula to only include those with a valid course_id
        $filtered = array_filter($curricula, function ($row) use ($validCourseIds) {
            return in_array($row['course_id'], $validCourseIds);
        });

        DB::table('curricula')->insert($filtered);
    }
}
