<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SemesterSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('semesters')->insert([
            // Semesters for 2025
            [
                'id' => 1,
                'name' => '1st - 2025',
                'year_id' => 1,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 16:30:00',
                'updated_at' => '2025-04-15 16:30:00',
            ],
            [
                'id' => 2,
                'name' => '2nd - 2025',
                'year_id' => 1,
                'status' => 'Active',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 16:40:00',
                'updated_at' => '2025-04-15 16:40:00',
            ],
            [
                'id' => 3,
                'name' => 'Rainy Season - 2025',
                'year_id' => 1,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 16:50:00',
                'updated_at' => '2025-04-15 16:50:00',
            ],
            // Semesters for 2024
            [
                'id' => 4,
                'name' => '1st - 2024',
                'year_id' => 2,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:00:00',
                'updated_at' => '2025-04-15 17:00:00',
            ],
            [
                'id' => 5,
                'name' => '2nd - 2024',
                'year_id' => 2,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:10:00',
                'updated_at' => '2025-04-15 17:10:00',
            ],
            [
                'id' => 6,
                'name' => 'Rainy Season - 2024',
                'year_id' => 2,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:20:00',
                'updated_at' => '2025-04-15 17:20:00',
            ],
            // Semesters for 2023
            [
                'id' => 7,
                'name' => '1st - 2023',
                'year_id' => 3,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:30:00',
                'updated_at' => '2025-04-15 17:30:00',
            ],
            [
                'id' => 8,
                'name' => '2nd - 2023',
                'year_id' => 3,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:40:00',
                'updated_at' => '2025-04-15 17:40:00',
            ],
            [
                'id' => 9,
                'name' => 'Rainy Season - 2023',
                'year_id' => 3,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 17:50:00',
                'updated_at' => '2025-04-15 17:50:00',
            ],
            // Semesters for 2022
            [
                'id' => 10,
                'name' => '1st - 2022',
                'year_id' => 4,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:00:00',
                'updated_at' => '2025-04-15 18:00:00',
            ],
            [
                'id' => 11,
                'name' => '2nd - 2022',
                'year_id' => 4,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:10:00',
                'updated_at' => '2025-04-15 18:10:00',
            ],
            [
                'id' => 12,
                'name' => 'Rainy Season - 2022',
                'year_id' => 4,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:20:00',
                'updated_at' => '2025-04-15 18:20:00',
            ],
            // Semesters for 2021
            [
                'id' => 13,
                'name' => '1st - 2021',
                'year_id' => 5,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:30:00',
                'updated_at' => '2025-04-15 18:30:00',
            ],
            [
                'id' => 14,
                'name' => '2nd - 2021',
                'year_id' => 5,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:40:00',
                'updated_at' => '2025-04-15 18:40:00',
            ],
            [
                'id' => 15,
                'name' => 'Rainy Season - 2021',
                'year_id' => 5,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 18:50:00',
                'updated_at' => '2025-04-15 18:50:00',
            ],
            // Semesters for 2020
            [
                'id' => 16,
                'name' => '1st - 2020',
                'year_id' => 6,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 19:00:00',
                'updated_at' => '2025-04-15 19:00:00',
            ],
            [
                'id' => 17,
                'name' => '2nd - 2020',
                'year_id' => 6,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 19:10:00',
                'updated_at' => '2025-04-15 19:10:00',
            ],
            [
                'id' => 18,
                'name' => 'Rainy Season - 2020',
                'year_id' => 6,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 19:20:00',
                'updated_at' => '2025-04-15 19:20:00',
            ],
            // Semesters for 2019
            [
                'id' => 19,
                'name' => '1st - 2019',
                'year_id' => 7,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 19:30:00',
                'updated_at' => '2025-04-15 19:30:00',
            ],
            [
                'id' => 20,
                'name' => '2nd - 2019',
                'year_id' => 7,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => '2025-04-15 19:40:00',
                'updated_at' => '2025-04-15 19:40:00',
            ],
            [
                'id' => 21,
                'name' => 'Rainy Season - 2019',
                'year_id' => 7,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            // Semesters for 2018
            [
                'id' => 22,
                'name' => '1st - 2018',
                'year_id' => 8,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 23,
                'name' => '2nd - 2018',
                'year_id' => 8,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 24,
                'name' => 'Rainy Season - 2018',
                'year_id' => 8,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            // Semesters for 2017
            [
                'id' => 25,
                'name' => '1st - 2017',
                'year_id' => 9,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 26,
                'name' => '2nd - 2017',
                'year_id' => 9,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 27,
                'name' => 'Rainy Season - 2017',
                'year_id' => 9,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            // Semesters for 2016
            [
                'id' => 28,
                'name' => '1st - 2016',
                'year_id' => 10,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 29,
                'name' => '2nd - 2016',
                'year_id' => 10,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
            [
                'id' => 30,
                'name' => 'Rainy Season - 2016',
                'year_id' => 10,
                'status' => 'Inactive',
                'is_approved' => 1,
                'is_completed' => 1,
                'created_at' => null,
                'updated_at' => null,
            ],
        ]);
    }
}
