<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class StudentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert user data
        DB::table('users')->insert([
            [
                'id' => 3,
                'user_uuid' => 'S-25-ST-0001',
                'name' => 'Mesfin Ayele Tesema',
                'email' => 'mesfin.ayele@sits.edu.et',
                'phone' => '0975228855',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Mesfin@8855'),
                'default_password' => 'Mesfin@8855',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-15 13:21:51',
                'updated_at' => '2025-04-15 13:21:51',
                'tenant_id' => 1,
            ],
            [
                'id' => 4,
                'user_uuid' => 'S-25-ST-0002',
                'name' => 'Abebe Kebede',
                'email' => 'abebe.kebede@sits.edu.et',
                'phone' => '0911223344',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Abebe@3344'),
                'default_password' => 'Abebe@3344',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 10:00:00',
                'updated_at' => '2025-04-16 10:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 5,
                'user_uuid' => 'S-25-ST-0003',
                'name' => 'Hana Tesfaye',
                'email' => 'hana.tesfaye@sits.edu.et',
                'phone' => '0911556677',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Hana@6677'),
                'default_password' => 'Hana@6677',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 11:00:00',
                'updated_at' => '2025-04-16 11:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 6,
                'user_uuid' => 'S-25-ST-0004',
                'name' => 'Kebede Alemu',
                'email' => 'kebede.alemu@sits.edu.et',
                'phone' => '0911889900',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Kebede@9900'),
                'default_password' => 'Kebede@9900',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 12:00:00',
                'updated_at' => '2025-04-16 12:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 7,
                'user_uuid' => 'S-25-ST-0005',
                'name' => 'Tigist Alemayehu',
                'email' => 'tigist.alemayehu@sits.edu.et',
                'phone' => '0911778899',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Tigist@8899'),
                'default_password' => 'Tigist@8899',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 13:00:00',
                'updated_at' => '2025-04-16 13:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 8,
                'user_uuid' => 'S-25-ST-0006',
                'name' => 'Dereje Bekele',
                'email' => 'dereje.bekele@sits.edu.et',
                'phone' => '0911990011',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Dereje@0011'),
                'default_password' => 'Dereje@0011',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 14:00:00',
                'updated_at' => '2025-04-16 14:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 9,
                'user_uuid' => 'S-25-ST-0007',
                'name' => 'Mulugeta Tadesse',
                'email' => 'mulugeta.tadesse@sits.edu.et',
                'phone' => '0911223345',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Mulugeta@3345'),
                'default_password' => 'Mulugeta@3345',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 15:00:00',
                'updated_at' => '2025-04-16 15:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 10,
                'user_uuid' => 'S-25-ST-0008',
                'name' => 'Alemayehu Bekele',
                'email' => 'alemayehu.bekele@sits.edu.et',
                'phone' => '0911445567',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Alemayehu@5567'),
                'default_password' => 'Alemayehu@5567',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 16:00:00',
                'updated_at' => '2025-04-16 16:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 11,
                'user_uuid' => 'S-25-ST-0009',
                'name' => 'Solomon Tadesse',
                'email' => 'solomon.tadesse@sits.edu.et',
                'phone' => '0911778890',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Solomon@8890'),
                'default_password' => 'Solomon@8890',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 17:00:00',
                'updated_at' => '2025-04-16 17:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 12,
                'user_uuid' => 'S-25-ST-0010',
                'name' => 'Marta Alemu',
                'email' => 'marta.alemu@sits.edu.et',
                'phone' => '0911889901',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Marta@9901'),
                'default_password' => 'Marta@9901',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 18:00:00',
                'updated_at' => '2025-04-16 18:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 13,
                'user_uuid' => 'S-25-ST-0011',
                'name' => 'Samuel Bekele',
                'email' => 'samuel.bekele@sits.edu.et',
                'phone' => '0911990012',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Samuel@0012'),
                'default_password' => 'Samuel@0012',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 19:00:00',
                'updated_at' => '2025-04-16 19:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 14,
                'user_uuid' => 'S-25-ST-0012',
                'name' => 'Betelhem Tadesse',
                'email' => 'betelhem.tadesse@sits.edu.et',
                'phone' => '0911223346',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Betelhem@3346'),
                'default_password' => 'Betelhem@3346',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 20:00:00',
                'updated_at' => '2025-04-16 20:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 15,
                'user_uuid' => 'S-25-ST-0013',
                'name' => 'Yohannes Alemayehu',
                'email' => 'yohannes.alemayehu@sits.edu.et',
                'phone' => '0911445568',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Yohannes@5568'),
                'default_password' => 'Yohannes@5568',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 21:00:00',
                'updated_at' => '2025-04-16 21:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 16,
                'user_uuid' => 'S-25-ST-0014',
                'name' => 'Rahel Mekonnen',
                'email' => 'rahel.mekonnen@sits.edu.et',
                'phone' => '0911556679',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Rahel@6679'),
                'default_password' => 'Rahel@6679',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 22:00:00',
                'updated_at' => '2025-04-16 22:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 17,
                'user_uuid' => 'S-25-ST-0015',
                'name' => 'Daniel Tadesse',
                'email' => 'daniel.tadesse@sits.edu.et',
                'phone' => '0911667780',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Daniel@7780'),
                'default_password' => 'Daniel@7780',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-16 23:00:00',
                'updated_at' => '2025-04-16 23:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 18,
                'user_uuid' => 'S-25-ST-0016',
                'name' => 'Mekdes Alemayehu',
                'email' => 'mekdes.alemayehu@sits.edu.et',
                'phone' => '0911778891',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Mekdes@8891'),
                'default_password' => 'Mekdes@8891',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-17 00:00:00',
                'updated_at' => '2025-04-17 00:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 19,
                'user_uuid' => 'S-25-ST-0017',
                'name' => 'Abel Bekele',
                'email' => 'abel.bekele@sits.edu.et',
                'phone' => '0911889902',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Abel@9902'),
                'default_password' => 'Abel@9902',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-17 01:00:00',
                'updated_at' => '2025-04-17 01:00:00',
                'tenant_id' => 1,
            ],
            [
                'id' => 20,
                'user_uuid' => 'S-25-ST-0018',
                'name' => 'Hana Mekonnen',
                'email' => 'hana.mekonnen@sits.edu.et',
                'phone' => '0911990013',
                'profile_img' => null,
                'email_verified_at' => null,
                'password' => Hash::make('Hana@0013'),
                'default_password' => 'Hana@0013',
                'password_changed' => 0,
                'remember_token' => null,
                'created_at' => '2025-04-17 02:00:00',
                'updated_at' => '2025-04-17 02:00:00',
                'tenant_id' => 1,
            ],
        ]);

        // Insert student data
        DB::table('students')->insert([
            [
                'user_id' => 3, // Link to the user created above
                'id' => 1,
                'id_no' => 'S-25-ST-0001',
                'first_name' => 'Mesfin',
                'middle_name' => 'Ayele',
                'last_name' => 'Tesema',
                'mobile_phone' => '0975228855',
                'office_phone' => '0954756431',
                'date_of_birth' => '1995-02-05',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Weldeamanuel Avenue, Hawassa, Sidama, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 1,
                'track_id' => 1,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-15 13:21:51',
                'updated_at' => '2025-04-15 13:21:51',
            ],
            [
                'user_id' => 4, // Link to the user created above
                'id' => 2,
                'id_no' => 'S-25-ST-0002',
                'first_name' => 'Abebe',
                'middle_name' => 'Kebede',
                'last_name' => 'Alemu',
                'mobile_phone' => '0911223344',
                'office_phone' => '0911334455',
                'date_of_birth' => '1998-06-15',
                'marital_status' => 'single',
                'sex' => 'M',
                'address' => 'Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 2,
                'track_id' => 2,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 10:00:00',
                'updated_at' => '2025-04-16 10:00:00',
            ],
            [
                'user_id' => 5, // Link to the user created above
                'id' => 3,
                'id_no' => 'S-25-ST-0003',
                'first_name' => 'Hana',
                'middle_name' => 'Tesfaye',
                'last_name' => 'Bekele',
                'mobile_phone' => '0911556677',
                'office_phone' => '0911667788',
                'date_of_birth' => '1997-03-12',
                'marital_status' => 'single',
                'sex' => 'F',
                'address' => 'Bole, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 3,
                'track_id' => 3,
                'year_id' => 1,
                'semester_id' => 2,
                'section_id' => 1,
                'created_at' => '2025-04-16 11:00:00',
                'updated_at' => '2025-04-16 11:00:00',
            ],
            [
                'user_id' => 6, // Link to the user created above
                'id' => 4,
                'id_no' => 'S-25-ST-0004',
                'first_name' => 'Kebede',
                'middle_name' => 'Alemu',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911889900',
                'office_phone' => '0911990011',
                'date_of_birth' => '1996-08-20',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Piassa, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 4,
                'track_id' => 4,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 12:00:00',
                'updated_at' => '2025-04-16 12:00:00',
            ],
            [
                'user_id' => 7, // Link to the user created above
                'id' => 5,
                'id_no' => 'S-25-ST-0005',
                'first_name' => 'Tigist',
                'middle_name' => 'Alemayehu',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911778899',
                'office_phone' => '0911889900',
                'date_of_birth' => '1999-01-15',
                'marital_status' => 'single',
                'sex' => 'F',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 5,
                'track_id' => 5,
                'year_id' => 1,
                'semester_id' => 2,
                'section_id' => 1,
                'created_at' => '2025-04-16 13:00:00',
                'updated_at' => '2025-04-16 13:00:00',
            ],
            [
                'user_id' => 8, // Link to the user created above
                'id' => 6,
                'id_no' => 'S-25-ST-0006',
                'first_name' => 'Dereje',
                'middle_name' => 'Bekele',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911990011',
                'office_phone' => '0911223344',
                'date_of_birth' => '1994-07-20',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Arat Kilo, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 6,
                'track_id' => 6,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 14:00:00',
                'updated_at' => '2025-04-16 14:00:00',
            ],
            [
                'user_id' => 9, // Link to the user created above
                'id' => 7,
                'id_no' => 'S-25-ST-0007',
                'first_name' => 'Mulugeta',
                'middle_name' => 'Tadesse',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911223345',
                'office_phone' => '0911334456',
                'date_of_birth' => '1993-05-10',
                'marital_status' => 'single',
                'sex' => 'M',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 7,
                'track_id' => 7,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 15:00:00',
                'updated_at' => '2025-04-16 15:00:00',
            ],
            [
                'user_id' => 10, // Link to the user created above
                'id' => 8,
                'id_no' => 'S-25-ST-0008',
                'first_name' => 'Alemayehu',
                'middle_name' => 'Bekele',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911445567',
                'office_phone' => '0911556678',
                'date_of_birth' => '1992-11-25',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Bole, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 8,
                'track_id' => 8,
                'year_id' => 2,
                'semester_id' => 2,
                'section_id' => 1,
                'created_at' => '2025-04-16 16:00:00',
                'updated_at' => '2025-04-16 16:00:00',
            ],
            [
                'user_id' => 11,
                'id' => 9,
                'id_no' => 'S-25-ST-0009',
                'first_name' => 'Solomon',
                'middle_name' => 'Tadesse',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911778890',
                'office_phone' => '0911889900',
                'date_of_birth' => '1995-01-01',
                'marital_status' => 'single',
                'sex' => 'M',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 7,
                'track_id' => 7,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 17:00:00',
                'updated_at' => '2025-04-16 17:00:00',
            ],
            [
                'user_id' => 12,
                'id' => 10,
                'id_no' => 'S-25-ST-0010',
                'first_name' => 'Marta',
                'middle_name' => 'Alemu',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911889901',
                'office_phone' => '0911990011',
                'date_of_birth' => '1996-02-15',
                'marital_status' => 'single',
                'sex' => 'F',
                'address' => 'Piassa, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 4,
                'track_id' => 4,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 18:00:00',
                'updated_at' => '2025-04-16 18:00:00',
            ],
            [
                'user_id' => 13,
                'id' => 11,
                'id_no' => 'S-25-ST-0011',
                'first_name' => 'Samuel',
                'middle_name' => 'Bekele',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911990012',
                'office_phone' => '0911223344',
                'date_of_birth' => '1994-07-20',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Arat Kilo, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 6,
                'track_id' => 6,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => 1,
                'created_at' => '2025-04-16 19:00:00',
                'updated_at' => '2025-04-16 19:00:00',
            ],
            [
                'user_id' => 14,
                'id' => 12,
                'id_no' => 'S-25-ST-0012',
                'first_name' => 'Betelhem',
                'middle_name' => 'Tadesse',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911223346',
                'office_phone' => '0911334456',
                'date_of_birth' => '1993-05-10',
                'marital_status' => 'single',
                'sex' => 'F',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 7,
                'track_id' => 7,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-16 20:00:00',
                'updated_at' => '2025-04-16 20:00:00',
            ],
            [
                'user_id' => 15,
                'id' => 13,
                'id_no' => 'S-25-ST-0013',
                'first_name' => 'Yohannes',
                'middle_name' => 'Alemayehu',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911445568',
                'office_phone' => '0911556678',
                'date_of_birth' => '1992-11-25',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Bole, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 8,
                'track_id' => 8,
                'year_id' => 2,
                'semester_id' => 2,
                'section_id' => null,
                'created_at' => '2025-04-16 21:00:00',
                'updated_at' => '2025-04-16 21:00:00',
            ],
            [
                'user_id' => 16,
                'id' => 14,
                'id_no' => 'S-25-ST-0014',
                'first_name' => 'Rahel',
                'middle_name' => 'Mekonnen',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911556679',
                'office_phone' => '0911667788',
                'date_of_birth' => '1993-05-10',
                'marital_status' => 'single',
                'sex' => 'F',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 7,
                'track_id' => 7,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-16 22:00:00',
                'updated_at' => '2025-04-16 22:00:00',
            ],
            [
                'user_id' => 17,
                'id' => 15,
                'id_no' => 'S-25-ST-0015',
                'first_name' => 'Daniel',
                'middle_name' => 'Tadesse',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911667780',
                'office_phone' => '0911778890',
                'date_of_birth' => '1995-01-01',
                'marital_status' => 'single',
                'sex' => 'M',
                'address' => 'Kazanchis, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 7,
                'track_id' => 7,
                'year_id' => 3,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-16 23:00:00',
                'updated_at' => '2025-04-16 23:00:00',
            ],
            [
                'user_id' => 18,
                'id' => 16,
                'id_no' => 'S-25-ST-0016',
                'first_name' => 'Mekdes',
                'middle_name' => 'Alemayehu',
                'last_name' => 'Kebede',
                'mobile_phone' => '0911778891',
                'office_phone' => '0911889900',
                'date_of_birth' => '1996-08-20',
                'marital_status' => 'Married',
                'sex' => 'F',
                'address' => 'Piassa, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 4,
                'track_id' => 4,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-17 00:00:00',
                'updated_at' => '2025-04-17 00:00:00',
            ],
            [
                'user_id' => 19,
                'id' => 17,
                'id_no' => 'S-25-ST-0017',
                'first_name' => 'Abel',
                'middle_name' => 'Bekele',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911889902',
                'office_phone' => '0911990011',
                'date_of_birth' => '1994-07-20',
                'marital_status' => 'Married',
                'sex' => 'M',
                'address' => 'Arat Kilo, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 6,
                'track_id' => 6,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-17 01:00:00',
                'updated_at' => '2025-04-17 01:00:00',
            ],
            [
                'user_id' => 20,
                'id' => 18,
                'id_no' => 'S-25-ST-0018',
                'first_name' => 'Hana',
                'middle_name' => 'Mekonnen',
                'last_name' => 'Tadesse',
                'mobile_phone' => '0911990013',
                'office_phone' => '0911223344',
                'date_of_birth' => '1994-07-20',
                'marital_status' => 'Married',
                'sex' => 'F',
                'address' => 'Arat Kilo, Addis Ababa, Ethiopia',
                'tenant_id' => 1,
                'program_id' => 6,
                'track_id' => 6,
                'year_id' => 2,
                'semester_id' => 1,
                'section_id' => null,
                'created_at' => '2025-04-17 02:00:00',
                'updated_at' => '2025-04-17 02:00:00',
            ],
        ]);
    }
}
